apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: backstage-all
  description: A collection of all Shieldpay entities, except users, groups, and templates
spec:
  targets:
    - ./all-apis.yaml
    - ./all-components.yaml
    - ./catalog/resources/database.yaml