apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: eslint-config
  description: "Eslint config and custom rules"
  annotations:
    backstage.io/techdocs-ref: dir:../
    github.com/project-slug: Shieldpay/optimus
  tags:
    - typescript
    - nodejs
spec:
  type: library
  lifecycle: production
