apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: github-npm-package-template
  title: GitHub Package NPM Template
  description: Template for creating a new NPM package in GitHub Packages
spec:
  owner: shieldpay
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the package
          ui:autofocus: true
          ui:options:
            rows: 5
        description:
          title: Description
          type: string
          description: Description of the package
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  # These steps are executed in the scaffolder backend, using data that we gathered
  # via the parameters above.
  steps:
    # Each step executes an action, in this case one templates files into the working directory.
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}

    # This step publishes the contents of the working directory to GitHub.
    - id: publish
      name: Create new service PR
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: 'feat: Add new package - ${{parameters.name}}'
        branchName: 'create-${{parameters.name}}'
        description: 'A new package that: ${{parameters.description}}'
        host: ${{parameters.host}}
        targetPath: 'packages/${{parameters.name}}'

  # Outputs are displayed to the user after a successful execution of the template.
  output:
    links:
      - title: Link to the new package PR
        url: ${{ steps['publish'].output.remoteUrl }}
