apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: ${{ values.description }}
  annotations:
    backstage.io/techdocs-ref: ./backend/services/${{ values.name }}
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
