apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: ${{ values.description }}
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
