apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "api-facade"
  description: "The API facade for the Shieldpay platform"
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: ironhide
  system: kyc   # The system this component belongs to
  lifecycle: production   # Supports  "experimental", "development", "production", "deprecated"
  providesApis:
    - api-facade # This is the name of the API we provide here
  consumesApis:
    - file-processor  # This is the name of the component that provides the API we consume here
  # dependsOn:
  #   - file-processor # This is the name of the component that provides the API we consume here
