apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "file-processor"
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: andrew-org-test/example-mono
spec:
  type: service
  owner: ironhide
  lifecycle: production
  system: kyc
  providesApis:
    - file-processor # This is the name of the API we provide here

