name: "Auth :: Deploy :: Dev"
on: workflow_dispatch
jobs:
  deploy-dev-preview:
    uses: ./.github/workflows/deploy-service.yml
    with:
      github-environment: DevPreview
      stage: $(echo ${{ github.actor }} | awk '{print tolower($0)}')
      service-name: "@shieldpay/auth"
      service-path: backend/services/auth
      lint-code: false
      test-code: false
      github-author: ${{ github.actor }}
      install-everything: true
    secrets:
      aws-role-arn: ${{ secrets.DEPLOYMENT_ROLE_ARN }}
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
