apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name: "test2"
  description: 
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
