name: "${{ values.name | capitalize }} :: Deploy :: Dev"

on: workflow_dispatch

jobs:
  deploy-dev-preview:
    uses: ./.github/workflows/deploy-service.yml
    with:
      github-environment: DevPreview
      stage: {% raw %}  $(echo ${{ github.actor }} | awk '{print tolower($0)}') {% endraw %}
      service-name: "@shieldpay/${{ values.name }}"
      service-path: backend/services/${{ values.name }}
      lint-code: false
      test-code: false
      github-author: {% raw %} ${{ github.actor }} {% endraw %}
    secrets:
      aws-role-arn: {% raw %} ${{ secrets.DEPLOYMENT_ROLE_ARN }} {% endraw %}
