name: "Admin :: Deploy :: Staging To Prod"

on: workflow_dispatch

jobs:
  deploy-staging:
    uses: ./.github/workflows/deploy-service.yml
    with:
      github-environment: Staging
      sentry-environment: "staging"
      stage: staging
      service-name: "@shieldpay/admin"
      service-path: backend/services/admin
      sourcemap-paths: ./dist
      lint-code: true
      test-code: true
      db: admin_test
    secrets:
      aws-role-arn: ${{ secrets.DEPLOYMENT_ROLE_ARN }}
      sentry-project: ${{ secrets.SENTRY_PROJECT }}
      sentry-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
      sentry-org: ${{ secrets.SENTRY_ORG }}

  deploy-production:
    uses: ./.github/workflows/deploy-service.yml
    needs: [deploy-staging]
    with:
      github-environment: Production
      sentry-environment: "production"
      stage: prod
      service-name: "@shieldpay/admin"
      service-path: backend/services/admin
      sourcemap-paths: ./dist
      lint-code: false
      test-code: false
    secrets:
      aws-role-arn: ${{ secrets.DEPLOYMENT_ROLE_ARN }}
      sentry-project: ${{ secrets.SENTRY_PROJECT }}
      sentry-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
      sentry-org: ${{ secrets.SENTRY_ORG }}
